import type { LabExperiment } from '../types/content'

export const labExperiments: LabExperiment[] = [
  {
    id: 'shader-garden',
    slug: 'shader-garden',
    name: 'Shader Garden',
    summary: 'An interactive WebGL shader playground built with Three.js.',
    description: 'Shader Garden lets users tweak live fragment shaders and save presets. It is used as a learning tool for GLSL and creative coding.',
    status: 'active',
    technologies: ['Three.js', 'GLSL', 'React', 'Zustand'],
    demoUrl: 'https://shader-garden.example.com',
    repositoryUrl: 'https://github.com/dylanhouston/shader-garden',
    image: '/lab/shader-garden.jpg',
  },
  {
    id: 'procedural-terrain',
    slug: 'procedural-terrain',
    name: 'Procedural Terrain',
    summary: 'Real-time terrain generation using layered noise and erosion simulation.',
    description: 'This experiment explores procedural mesh generation and GPU-based erosion. It runs in the browser and exports heightmaps for use in game engines.',
    status: 'prototype',
    technologies: ['Three.js', 'TypeScript', 'Simplex Noise', 'WebGL'],
    repositoryUrl: 'https://github.com/dylanhouston/procedural-terrain',
    image: '/lab/procedural-terrain.jpg',
  },
  {
    id: 'ai-chat-tool',
    slug: 'ai-chat-tool',
    name: 'AI Chat Tool',
    summary: 'A local-first chat interface for comparing LLM responses side by side.',
    description: 'This experiment compares outputs from multiple language models and lets users save conversation branches. Built with privacy in mind, conversations stay in local storage.',
    status: 'active',
    technologies: ['React', 'TypeScript', 'OpenAI', 'Zustand'],
    repositoryUrl: 'https://github.com/dylanhouston/ai-chat-tool',
    demoUrl: 'https://ai-chat-tool.example.com',
    image: '/lab/ai-chat-tool.jpg',
  },
  {
    id: 'tiny-physics',
    slug: 'tiny-physics',
    name: 'Tiny Physics',
    summary: 'A miniature 2D physics engine for the web.',
    description: 'Tiny Physics implements rigid body dynamics, collision detection, and constraints in a few hundred lines of TypeScript.',
    status: 'prototype',
    technologies: ['TypeScript', 'Canvas API', 'Verlet Integration'],
    repositoryUrl: 'https://github.com/dylanhouston/tiny-physics',
    image: '/lab/tiny-physics.jpg',
  },
]
